<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\bunny.obj" />
    <None Remove="Resources\fur.jpg" />
    <None Remove="Resources\grass.jpg" />
    <None Remove="Resources\ground.obj" />
    <None Remove="Resources\petal.png" />
    <None Remove="Resources\sakura_tree.obj" />
    <None Remove="Resources\skybox.png" />
    <None Remove="Resources\teapot.obj" />
    <None Remove="Shaders\FragmentShader.frag" />
    <None Remove="Shaders\VertexShader.vert" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\bunny.obj" />
    <EmbeddedResource Include="Resources\fur.jpg" />
    <EmbeddedResource Include="Resources\grass.jpg" />
    <EmbeddedResource Include="Resources\ground.obj" />
    <EmbeddedResource Include="Resources\petal.png" />
    <EmbeddedResource Include="Resources\sakura_tree.obj" />
    <EmbeddedResource Include="Resources\skybox.png" />
    <EmbeddedResource Include="Resources\teapot.obj" />
    <EmbeddedResource Include="Shaders\FragmentShader.frag" />
    <EmbeddedResource Include="Shaders\VertexShader.vert" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET" Version="2.22.0" />
    <PackageReference Include="Silk.NET.OpenGL.Extensions.ImGui" Version="2.22.0" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>

</Project>
